#!/usr/bin/env bash
# Nginx port 80 - Update symbolic link sites-available/default to sites-enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
